apiVersion: v1
kind: Service
metadata:
  labels:
    app: gpt2gotmodel
    app.kubernetes.io/part-of: gotmining
  name: gpt2gotmodel
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: gpt2gotmodel
