apiVersion: v1
kind: ConfigMap
metadata:
  name: gotmining-cm
data:
  GPT2SERVICEURL: "https://gotmining-backend-group1.apps.science-cluster.sandbox2009.opentlc.com"
  DOLLYSERVICEURL: "https://dollyv2-gotmining-backend-group1.apps.science-cluster.sandbox2009.opentlc.com"
  AWS_COMPREHEND_ENDPOINT_ARN: "arn:aws:comprehend:eu-central-1:348083399151:document-classifier-endpoint/gotmining"