apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gotminingui
    app.kubernetes.io/part-of: gotmining
  name: gotminingui
  annotations:
    app.openshift.io/connects-to: >-
      [{"apiVersion":"serving.knative.dev/v1","kind":"Service","name":"gpt2gotmodel"},{"apiVersion":"apps/v1","kind":"Deployment","name":"gpt2gotmodel"},{"apiVersion":"apps/v1","kind":"Deployment","name":"dolly"}]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotminingui
  template:
    metadata:
      labels:
        app: gotminingui
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: gotmining-cm
          - secretRef:
              name: gotmining-secret
        image: quay.io/mdargatz/gotminingui:latest
        name: gotmining-frontend
        ports:
          - containerPort: 3000
      restartPolicy: Always
