apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: gpu-nodes-normal
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-rpz5t-qbwmp
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-rpz5t-qbwmp
      machine.openshift.io/cluster-api-machineset: cluster-rpz5t-qbwmp-gpu-fat-eu-central-1b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-rpz5t-qbwmp
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: cluster-rpz5t-qbwmp-gpu-fat-eu-central-1b
    spec:
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: eu-central-1b
            region: eu-central-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: p3.2xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 120
                volumeType: gp2
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-rpz5t-qbwmp-worker-sg
          kind: AWSMachineProviderConfig
          tags:
            - name: kubernetes.io/cluster/cluster-rpz5t-qbwmp
              value: owned
            - name: owner
              value: unknown
            - name: platform
              value: RHPDS
            - name: uuid
              value: 742bcb12-a1a8-5943-8b50-78e1cc6c3105
            - name: Stack
              value: project ocp4-cluster-rpz5t
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: rpz5t
          ami:
            id: ami-002eb441f329ccb0f
          deviceIndex: 0
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-rpz5t-qbwmp-private-eu-central-1c
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-rpz5t-qbwmp-worker-profile
