apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  annotations:
    machine.openshift.io/GPU: '1'
    machine.openshift.io/memoryMb: '16384'
    machine.openshift.io/vCPU: '4'
  name: rosa-gpu-worker-eu-central-1a
  namespace: openshift-machine-api
  labels:
    hive.openshift.io/machine-pool: worker
    hive.openshift.io/managed: 'true'
    machine.openshift.io/cluster-api-cluster: rosa-gpu
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: rosa-gpu
      machine.openshift.io/cluster-api-machineset: rosa-gpu-worker-eu-central-1a
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: rosa-gpu
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: rosa-gpu-worker-eu-central-1a
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: eu-central-1a
            region: eu-central-1
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: g4dn.xlarge
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 300
                volumeType: gp3
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - rosa-8cr9m-tzkd4-worker-sg
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/rosa-gpu
              value: owned
            - name: red-hat-clustertype
              value: rosa
            - name: red-hat-managed
              value: 'true'
          deviceIndex: 0
          ami:
            id: ami-09aca7755cacbe28d
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - rosa-gpu-private-eu-central-1a
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: rosa-8cr9m-tzkd4-worker-profile

